### ISSUE TITLE
4.5.0-rc7 issue with sch_cake

### ISSUE THREAD

**Issue by dtaht** [dtaht/sch_cake#20]
make[1]: Entering directory '/home/d/git/linux/tim'
  CC [M]  /home/d/git/sch_cake/sch_cake.o
/home/d/git/sch_cake/sch_cake.c: In function ‘cake_enqueue’:
/home/d/git/sch_cake/sch_cake.c:662:3: error: implicit declaration of function ‘qdisc_tree_reduce_backlog’ [-Werror=implicit-function-declaration]
   qdisc_tree_reduce_backlog(sch, 1, len);

**Comment by chromi** [comment]
> On 13 Apr, 2016, at 23:14, Dave Täht notifications@github.com wrote:
> 
> /home/d/git/sch_cake/sch_cake.c:662:3: error: implicit declaration of function ‘qdisc_tree_reduce_backlog’ [-Werror=implicit-function-declaration]

Yes, apparently qdisc_tree_decrease_qlen() was replaced by this about a month ago in net-next.  The old code is still present to support older kernels, with #ifdefs - need to find a way to make it autodetect.

Also, for some reason the new code is unstable, but only when diffserv is turned on.  Still troubleshooting that, which is why I haven’t announced it.
- Jonathan Morton

**Comment by Trucido** [comment]
Sorry for responding out-of-topic-ish here, Unsure if issue or not, but speaking of compiler warnings, is this normal? I can't really understand the code and not sure if this var is important or not. this was built against 4.4.10 (Debian) but also occurs in 4.4.9, did stuff change? I haven't had the chance to test it compiled against an older kernel yet.

```
sch_cake.c: In function ‘cake_dequeue’:
sch_cake.c:792:6: warning: unused variable ‘i’ [-Wunused-variable]
```

here's the code snippit I found the variable s32 i;

```
static struct sk_buff *cake_dequeue(struct Qdisc *sch)
{
    struct cake_sched_data *q = qdisc_priv(sch);
    struct sk_buff *skb;
    struct cake_tin_data *b = &q->tins[q->cur_tin];
    struct cake_flow *flow;
    struct list_head *head;
    u16 prev_drop_count, prev_ecn_mark, prev_backlog;
    u16 deferred_hosts;
    static struct sk_buff *cake_dequeueu32 len;
    codel_time_t now = ktime_get_ns();
    s32 i;
    codel_time_t delay;
    bool src_blocked = false, dst_blocked = false;
```

If stuff changed or was backported to 4.4, do we need this for 4.4 (and presumably 4.5) now and not just 4.6.x?

```
#if KERNEL_VERSION(4, 6, 0) > LINUX_VERSION_CODE
#define qdisc_tree_reduce_backlog(_a,_b,_c) qdisc_tree_decrease_qlen(_a,_b)
#endif
```

It seems to build and work fine, though I haven't run any flent tests. I'm concerned perhaps some of these functions aren't actually working as intended. I'm using this small iproute2 4.4 patch to add cake for iproute 4.3 https://gist.github.com/hnyman/b35bf1e2501ad7dd08d4 (950-add-cake-to-tc.patch but not original_tc-adv_changes_to_430.patch)
Also, it would be nice if sch_cake could be integrated into dkms for non-openwrt targets so any new kernels would automatically build it.

**Comment by hnyman** [comment]
I ran into this issue when I tested kernel 4.4.10 for ar71xx platform (on LEDE, the Openwrt spinoff). I temporarily dropped cake from my build to get the build compiled (as I did not want to spend time to fix cake).  

The same source base compiles just fine for 4.1, but toggling kernel to 4.4 breaks cake compilation. I think that it is due to qdisc/codel backports done in connection with the 4.4 update. E.g. on LEDE side the qdisc_tree_reduce_backlog changes are backported to 4.4 (from 4.6?):
-    https://git.lede-project.org/?p=source.git;a=commitdiff;h=fad8bdfa40df8636a52d770bbab010086c1976ec
-    https://git.lede-project.org/?p=source.git;a=blob;f=target/linux/generic/patches-4.4/031-net_sched-update-hierarchical-backlog-too.patch;h=eb34eea4a6b30041d8f86ca18eca9a8a960b9291;hb=fad8bdfa40df8636a52d770bbab010086c1976ec

As far as I know, Openwrt & LEDE will likely have the next releases based on kernel 4.4, so if cake is to have any relevance in that tester/user base, it would be great to have the code fixed also for 4.4.

(And the unused "i" variable should be eliminated in any case.)

Key errors below:

```
make[3]: Entering directory '/Openwrt/lede/build_dir/target-mips_34kc_musl-1.1.14/linux-ar71xx_generic/linux-4.4.10'
  CC [M]  /Openwrt/lede/build_dir/target-mips_34kc_musl-1.1.14/linux-ar71xx_generic/sched-cake-2016-git/sch_cake.o
/Openwrt/lede/build_dir/target-mips_34kc_musl-1.1.14/linux-ar71xx_generic/sched-cake-2016-git/sch_cake.c: In function 'cake_enqueue':
/Openwrt/lede/build_dir/target-mips_34kc_musl-1.1.14/linux-ar71xx_generic/sched-cake-2016-git/sch_cake.c:62:45: error: implicit declaration of function 'qdisc_tree_decrease_qlen' [-Werror=implicit-function-declaration]
 #define qdisc_tree_reduce_backlog(_a,_b,_c) qdisc_tree_decrease_qlen(_a,_b)
                                             ^
/Openwrt/lede/build_dir/target-mips_34kc_musl-1.1.14/linux-ar71xx_generic/sched-cake-2016-git/sch_cake.c:663:3: note: in expansion of macro 'qdisc_tree_reduce_backlog'
   qdisc_tree_reduce_backlog(sch, 1, len);
   ^
/Openwrt/lede/build_dir/target-mips_34kc_musl-1.1.14/linux-ar71xx_generic/sched-cake-2016-git/sch_cake.c: In function 'cake_dequeue':
/Openwrt/lede/build_dir/target-mips_34kc_musl-1.1.14/linux-ar71xx_generic/sched-cake-2016-git/sch_cake.c:792:6: warning: unused variable 'i' [-Wunused-variable]
  s32 i;
      ^
cc1: some warnings being treated as errors

```

**Comment by Trucido** [comment]
I guess the unused var is currently harmless but to add to the above post - It appears that both net_sched patches are in the latest kernel 4.4 queue for inclusion in 4.4.11
- https://git.kernel.org/cgit/linux/kernel/git/stable/stable-queue.git/commit/?id=bbda4af0cf2ddb895d6a8b6d9c93912bff82a8f0

as a temporary fix it might work to just change the #if KERNEL_VERSION's so it declares those two functions but the FIX ME next to one of them is concerning if the code isn't up to par.

Also, thanks for the cake tc patch @hnyman I also wasn't aware of LEDE until now.

**Comment by hnyman** [comment]
I fixed my LEDE build by defining a patch for cake that changes the minimum kernel version for the macro definition and deletes the unused variable:

```
perus@ub1604:$ cat kmod-sched-cake/patches/100-fix-compilation.patch 
--- a/sch_cake.c
+++ b/sch_cake.c
@@ -58,7 +58,7 @@
 #endif
 #include "codel5.h"

-#if KERNEL_VERSION(4, 6, 0) > LINUX_VERSION_CODE
+#if KERNEL_VERSION(4, 4, 0) > LINUX_VERSION_CODE
 #define qdisc_tree_reduce_backlog(_a,_b,_c) qdisc_tree_decrease_qlen(_a,_b)
 #endif

@@ -789,7 +789,6 @@ static struct sk_buff *cake_dequeue(stru
    u16 deferred_hosts;
    u32 len;
    codel_time_t now = ktime_get_ns();
-   s32 i;
    codel_time_t delay;
    bool src_blocked = false, dst_blocked = false;

```

 @Trucido  You are welcome. Good to hear that somebody finds the cake tc patch useful

**Comment by Trucido** [comment]
@hnyman 

Thanks - that does work for now, though as previously stated this FIXME does concern me

``` c
qdisc_tree_reduce_backlog(sch, dropped - same_flow, 0 /* FIXME */);
```

And we still need a real fix though from whomever maintains sch_cake since the code needs to depend on presumably sublevel 11 or higher (once 4.4.11 releases) and openwrt platforms with these patches already backported should be aware of it too. Detecting this may also prove problematic on some platforms such as Debian which strip the sublevel version. It's still an easy manual bandaid fix if people are aware of it though. I may look into some of the other scheds in LEDE and the sqm-scripts forks floating around here for an alternative in the meantime if this proves unreliable.

Edit: Though on Debian I just noticed the Makefile in linux-headers still has the sublevel intact so perhaps that won't be an issue to do something like this after 4.4.11 releases with the sched changes.

``` c
#if KERNEL_VERSION(4, 4, 11) > LINUX_VERSION_CODE
```

(excuse my crude C if I have this backwards here, not entirely sure how these work)

Edit2: kernel 4.4.11 and 4.5.5 released today with the sched changes, so this issue should be bumped. Also, it seems unstable with above bandaid fix on 4.4.11 and without bandaid fix on 4.4.10 so something is fishy.

**Comment by ldir-EDB0** [comment]
The unused variable s32 i is a pretty innocuous left over from the previous commit where bandwidth charging to all lower tins in addition to the current one was removed.  i was a simple for loop counter.  I have now removed the unused variable.

The kernel version thing needs a bit more thinking about - you can't just say > 4.4.11 since 4.5.0-4 will still have the old API.

**Comment by moeller0** [comment]
Hi Kevin, hi Jonathan,

> On May 19, 2016, at 13:53 , Kevin Darbyshire-Bryant notifications@github.com wrote:
> 
> The unused variable s32 i is a pretty innocuous left over from the previous commit where bandwidth charging to all lower tins in addition to the current one was removed. i was a simple for loop counter. I have now removed the unused variable.
> 
> The kernel version thing needs a bit more thinking about - you can’t just say > 4.4.11 since 4.5.0-4 will still have the old API.

```
This is a good argument to upstream cake now, “warts and all”. Cake seems to work as advertized and it is not that it will be impossible to fix behavior/bugs/etc once it is upstream. Maybe disable all non-essential/controversial features first like the squash/squish functionality and the max_packet size statistic report that I really like, and then do further development against the upstream kernel… This will not fix the current issues, but at least it will reduce the need to do subversion matching against even more kernel versions… Are there any known show-stoppers to this course of action?
```

Best Regards
    Sebastian

**Comment by ldir-EDB0** [comment]
Well Sebastian, the qdisc_tree_reduce_backlog(sch, dropped - same_flow, 0 /\* FIXME */) in cake_enqueue is a bit of a problem.  This is a (hopefully rarely) executed codepath which drops packets from the qdisc when it is exceeding its maximum memory consumption threshold.

It calls 'cake_drop' to discard a packet from the fattest flow until memory consumption has gone below the limit.  Whilst it keeps track of how many packets it discards, it does not keep track of how many bytes (skblen)   When not distracted by other things I keep looking at this and trying to work out how to fix it.

**Comment by chromi** [comment]
> On 19 May, 2016, at 15:32, Kevin Darbyshire-Bryant notifications@github.com wrote:
> 
> Well Sebastian, the qdisc_tree_reduce_backlog(sch, dropped - same_flow, 0 /\* FIXME */) in cake_enqueue is a bit of a problem. This is a (hopefully rarely) executed codepath which drops packets from the qdisc when it is exceeding is maximum memory consumption threshold.
> 
> It calls 'cake_drop' to discard a packet from the fattest flow until memory consumption has gone below the limit. Whilst it keeps track of how many packets it discards, it does not keep track of how many bytes (skblen) When not distracted by other things I keep looking at this and trying to work out how to fix it.

It’s also on my radar.

I do think getting cake upstreamed is a worthy goal, especially since the relevant kernel APIs keep changing like this.
- Jonathan Morton

**Comment by Trucido** [comment]
@chromi 

> Also, for some reason the new code is unstable, but only when diffserv is turned on.  Still troubleshooting that, which is why I haven’t announced it.

Was the cause of this ever found? I traced my kernel BUG:'s and stack traces back to diffserv4 (I didn't realize the .qos script I was using was setting it until I checked the .state file) but I don't have much useful information to provide, they always stack traced with  _raw_spin_lock_irqsave and some scheduler-related wake_up\* and entry_SYSCALL_64_fastpath calls. for some reason compiling kernels repeatedly was able to trigger it somewhat reliably, perhaps the cpu contention combined with ssh network traffic was exposing it.

**Comment by chromi** [comment]
> On 20 May, 2016, at 22:37, Trucido notifications@github.com wrote:
> 
> Also, for some reason the new code is unstable, but only when diffserv is turned on. Still troubleshooting that, which is why I haven’t announced it.
> 
> Was the cause of this ever found? I traced my kernel BUG:'s and stack traces back to diffserv4 (I didn't realize the .qos script I was using was setting it until I checked the .state file) but I don't have much useful information to provide, they always stack traced with _raw_spin_lock_irqsave and some scheduler-related wake_up\* and entry_SYSCALL_64_fastpath calls. for some reason compiling kernels alone was able to trigger it somewhat reliably, perhaps with cpu contention and ssh network traffic it was somehow triggering it.

The instability _I_ noticed was fixed when Kevin noticed a typo in the diffserv-llt setup code.  This wouldn’t have affected any other Diffserv mode.

Since then I haven’t had any instability with Cake.  (I eat my own dogfood, so it’s running on my main firewall machine, which admittedly has only one CPU.)
- Jonathan Morton

**Comment by Trucido** [comment]
> The instability _I_ noticed was fixed when Kevin noticed a typo in the diffserv-llt setup code.  This wouldn’t have affected any other Diffserv mode.
> 
> Since then I haven’t had any instability with Cake.  (I eat my own dogfood, so it’s running on my main firewall machine, which admittedly has only one CPU.)

Hmm, must be something else then. Also my CPU topology is quite different, I was testing on dual xeons. I'll investigate further when I have some time.

**Comment by ldir-EDB0** [comment]
The diffserv-llt fix https://github.com/dtaht/sch_cake/commit/659ba6e9fa09565c2e24209bd97fced98de6dfc0 - looked like a copy/paste typo to me, so I fixed it.  Without the fix my router would go for extended lunch breaks :-)  Cake has been very stable for me, the brief period of trouble introduced by diffserv-llt was obviously related to its introduction and the culprit found :-)  Again though, like Jonathan, my 'test bed' home router is single cpu only, now running linux 4.4.11.

**Comment by Trucido** [comment]
I've reproduced my issues without sch_cake under similar conditions, so sch_cake doesn't appear to be at fault here. It was another module (or lack thereof). False alarm, sorry.

**Comment by jukkapirinen** [comment]
@hnyman I could not get the cake compiled with the patches. Which patches I should use with LEDE and where to place them? Should I put some under iproute2 package?
I'm using lede r403 and cake from yesterday https://github.com/dtaht/sch_cake/commit/6427d9afd8da44696a66a7f55270aacfba052dee .

I then compiled it with tc-adv and got cake working pretty well in LAN.
But the speeds with ipv6 is very bad when SQM enabled, with both fq_codel and cake.
And also with Wifi SQM seems not to be working very well...

**Comment by hnyman** [comment]
@bbogey 
The cake patch is unnecessary since https://github.com/dtaht/sch_cake/commit/63b7538910ede8624c14dff913d9769a8a479c9c and https://github.com/dtaht/sch_cake/commit/df40fa23fbbed9f652e201058fc730f37ae7513c implemented the same changes and you are using a more recent version of cake. Just remove the cake patch and use just the Makefile. (I have been using df40fa23fbbed9f652e201058fc730f37ae7513c as my cake revision, but newer commits should also compile just fine)

You still need the 950..patch for iproute2 (or you can use the tc-adv, but that is an older tc version, I think)

I updated my gist and left just the Makefile and 950...patch
https://gist.github.com/hnyman/b35bf1e2501ad7dd08d4
